theme: jekyll-theme-minimal
title: Supermarket Expenses 
description: This application was done as a pet project to learn flutter. Please let me know if there are any issues or if you would like to add something by contacting me at supermarketexpenses@gmail.com

<html>
<body>
<h1> Privacy Policy for Supermarket Expenses </h1>

<p>Last updated: December 06, 2022

This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the TermsFeed Privacy Policy Generator.</p>
